In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import sklearn

In [3]:
first = pd.read_csv('1.csv')
first

,log_entry_time,impression_id,partner_id,campaign_id,ad_group_id,private_contract_id,audience_id,creative_id,ad_format,frequency,...,processed_time,device_make,device_model,rendering_context,carrier_id,temperature_in_celsius_name,temperature_bucket_start_in_celsius_name,temperature_bucket_end_in_celsius_name,impression_placement_id,advertiser_id
0,2020-10-02 02:31:05,dd39a58b-935b-4b59-b1d2-293c34132185,wsc5r0j,pey7wjw,l16k4pm,x4wccoj,NaN,bkqbfyvb,640x360,5,...,2020-10-02 02:39:04.159,Amazon,AFTMM,InApp,NaN,12.12,10.0,18.0,NaN,3ysyqec
1,2020-10-02 11:06:09,9f33b60d-6ecf-44a2-b8d3-2f22c7be61e5,wsc5r0j,37mbq70,985jsza,vyhvbql,k7orynn,3j4iywjn,9544x9544,0,...,2020-10-02 11:15:36.586,Samsung,SM-G970U1,Other,NaN,15.28,10.0,18.0,50054,3ysyqec
2,2020-10-02 02:35:08,75339cae-023f-4530-b406-27e088e26c00,wsc5r0j,pey7wjw,l16k4pm,x4wccoj,NaN,bkqbfyvb,640x360,2,...,2020-10-02 02:39:17.864,LG,Smart+ TV,Other,NaN,17.11,10.0,18.0,NaN,3ysyqec
3,2020-10-02 02:32:31,c17ef430-9798-4479-8751-7b460b76cd56,wsc5r0j,el02c6n,exazlvq,2irdgp0,NaN,z78nzkwb,640x360,0,...,2020-10-02 02:39:21.849,Roku,Digital Video player,InApp,NaN,14.26,10.0,18.0,i79zj-2z9zw,3ysyqec
4,2020-10-02 02:32:54,3bc7ec45-7392-4fa0-848f-c5ae53388c55,wsc5r0j,37mbq70,985jsza,vyhvbql,k7orynn,e3ttvsvt,9544x9544,0,...,2020-10-02 02:39:22.396,Samsung,SM-G965U,Other,NaN,NaN,NaN,NaN,8019,3ysyqec
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12965573,2020-10-01 17:27:06,8b8ef6c9-838f-4847-a220-c43e3063128e,wsc5r0j,el02c6n,exazlvq,2irdgp0,NaN,z78nzkwb,640x360,0,...,2020-10-01 17:33:37.994,Roku,Digital Video player,InApp,NaN,NaN,NaN,NaN,i79zj-2z9zw,3ysyqec
12965574,2020-10-01 17:27:14,7468003f-fa5b-464a-98a4-968bec0f6087,wsc5r0j,el02c6n,exazlvq,2irdgp0,NaN,vm4zejhx,640x360,0,...,2020-10-01 17:33:38.103,Roku,Digital Video player,InApp,NaN,22.05,18.0,24.0,i79zj-2z9zw,3ysyqec
12965575,2020-10-01 17:28:45,2525a378-9270-4297-b385-2bc085faeeb6,wsc5r0j,el02c6n,exazlvq,2irdgp0,NaN,z78nzkwb,640x360,0,...,2020-10-01 17:33:41.229,Roku,Digital Video player,InApp,NaN,NaN,NaN,NaN,i79zj-2z9zw,3ysyqec
12965576,2020-10-01 17:29:57,16b9d9e1-4094-4198-898f-ce55002a1118,wsc5r0j,el02c6n,exazlvq,2irdgp0,NaN,vm4zejhx,640x360,0,...,2020-10-01 17:33:52.933,Roku,Digital Video player,InApp,NaN,22.22,18.0,24.0,i79zj-2z9zw,3ysyqec
12965577,2020-10-01 17:30:56,99536295-93dd-4c08-9b87-a08ebedc4208,wsc5r0j,37mbq70,985jsza,vyhvbql,k7orynn,e3ttvsvt,9544x9544,0,...,2020-10-01 17:33:53.48,NaN,Chrome - Windows,Other,NaN,NaN,NaN,NaN,56753,3ysyqec

In [5]:
first.columns

Index(['log_entry_time', 'impression_id', 'partner_id', 'campaign_id',
       'ad_group_id', 'private_contract_id', 'audience_id', 'creative_id',
       'ad_format', 'frequency', 'supply_vendor', 'supply_vendor_publisher_id',
       'deal_id', 'site', 'referrer_categories_list', 'fold_position',
       'user_hour_of_week', 'user_agent', 'ip_address', 'country', 'region',
       'metro', 'city', 'device_type', 'os_family', 'os', 'browser', 'recency',
       'language_code', 'media_cost', 'fee_feature_cost',
       'data_usage_total_cost', 'ttd_cost_in_usd', 'partner_cost_in_usd',
       'advertiser_cost_in_usd', 'latitude', 'longitude', 'zip_code',
       'processed_time', 'device_make', 'device_model', 'rendering_context',
       'carrier_id', 'temperature_in_celsius_name',
       'temperature_bucket_start_in_celsius_name',
       'temperature_bucket_end_in_celsius_name', 'impression_placement_id',
       'advertiser_id'],
      dtype='object')

In [6]:
first = first.set_axis(['log_entry_time', 'impression_id', 'partner_id', 'campaign_id',
       'ad_group_id', 'private_contract_id', 'audience_id', 'creative_id',
       'ad_format', 'frequency', 'supply_vendor', 'supply_vendor_publisher_id',
       'deal_id', 'site', 'referrer_categories_list', 'fold_position',
       'user_hour_of_week', 'user_agent', 'ip_address', 'country', 'region',
       'metro', 'city', 'device_type', 'os_family', 'os', 'browser', 'recency',
       'language_code', 'media_cost', 'fee_feature_cost',
       'data_usage_total_cost', 'ttd_cost_in_usd', 'partner_cost_in_usd',
       'advertiser_cost_in_usd', 'latitude', 'longitude', 'zip_code',
       'processed_time', 'device_make', 'device_model', 'rendering_context',
       'carrier_id', 'temperature_in_celsius_name',
       'temperature_bucket_start_in_celsius_name',
       'temperature_bucket_end_in_celsius_name', 'impression_placement_id',
       'advertiser_id'], axis='columns')

In [7]:
second = pd.read_csv('2.csv')
second = second.set_axis(['log_entry_time', 'impression_id', 'partner_id', 'campaign_id',
       'ad_group_id', 'private_contract_id', 'audience_id', 'creative_id',
       'ad_format', 'frequency', 'supply_vendor', 'supply_vendor_publisher_id',
       'deal_id', 'site', 'referrer_categories_list', 'fold_position',
       'user_hour_of_week', 'user_agent', 'ip_address', 'country', 'region',
       'metro', 'city', 'device_type', 'os_family', 'os', 'browser', 'recency',
       'language_code', 'media_cost', 'fee_feature_cost',
       'data_usage_total_cost', 'ttd_cost_in_usd', 'partner_cost_in_usd',
       'advertiser_cost_in_usd', 'latitude', 'longitude', 'zip_code',
       'processed_time', 'device_make', 'device_model', 'rendering_context',
       'carrier_id', 'temperature_in_celsius_name',
       'temperature_bucket_start_in_celsius_name',
       'temperature_bucket_end_in_celsius_name', 'impression_placement_id',
       'advertiser_id'], axis='columns')

In [8]:
second

,log_entry_time,impression_id,partner_id,campaign_id,ad_group_id,private_contract_id,audience_id,creative_id,ad_format,frequency,...,processed_time,device_make,device_model,rendering_context,carrier_id,temperature_in_celsius_name,temperature_bucket_start_in_celsius_name,temperature_bucket_end_in_celsius_name,impression_placement_id,advertiser_id
0,2020-09-21 14:43:59,feeb8dbc-212a-4fba-8f8e-322431e625bf,wsc5r0j,el02c6n,exazlvq,2irdgp0,NaN,z78nzkwb,640x360,0,...,2020-09-21 15:04:23.377,Roku,Digital Video player,InApp,NaN,NaN,NaN,NaN,i79zj-2z9zw,3ysyqec
1,2020-09-21 14:41:54,b768bf1c-a433-44a1-9614-87f983118c94,wsc5r0j,pey7wjw,fcucjsu,wt0zmqf,1qh4zg7,vwzako4t,640x360,3,...,2020-09-21 15:05:00.877,Roku,Digital Video player,InApp,NaN,17.86,10.0,18.0,NaN,3ysyqec
2,2020-09-21 21:34:20,742e59e3-9283-4f32-81eb-7ccfe01e13ae,wsc5r0j,pey7wjw,fcucjsu,wt0zmqf,1qh4zg7,vwzako4t,640x360,3,...,2020-09-21 21:42:57.189,Roku,Digital Video player,InApp,NaN,NaN,NaN,NaN,NaN,3ysyqec
3,2020-09-21 21:34:08,9c298ba2-32e8-4a6e-adad-32f2f004bb95,wsc5r0j,pey7wjw,fcucjsu,wt0zmqf,1qh4zg7,vwzako4t,640x360,4,...,2020-09-21 21:43:25.823,Roku,Digital Video player,InApp,NaN,NaN,NaN,NaN,NaN,3ysyqec
4,2020-09-21 20:27:32,66cea51b-267b-4a2e-96c0-fcd276e2521c,wsc5r0j,el02c6n,exazlvq,2irdgp0,NaN,z78nzkwb,640x360,0,...,2020-09-21 20:45:31.18,Roku,Digital Video player,InApp,NaN,18.90,18.0,24.0,i79zj-2z9zw,3ysyqec
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10820540,2020-09-19 10:35:22,8d51f582-375b-435b-9b34-7f198c41d3d4,wsc5r0j,pey7wjw,fcucjsu,wt0zmqf,1qh4zg7,vwzako4t,640x360,4,...,2020-09-19 10:39:23.839,Roku,Digital Video player,InApp,NaN,9.15,0.0,10.0,NaN,3ysyqec
10820541,2020-09-19 03:32:45,03abcb43-59b4-4b3e-b024-736d504b1e5c,wsc5r0j,pey7wjw,fcucjsu,wt0zmqf,1qh4zg7,vwzako4t,640x360,4,...,2020-09-19 03:37:32.437,Microsoft,XBOX One,InApp,NaN,26.87,24.0,30.0,NaN,3ysyqec
10820542,2020-09-19 10:22:29,a9b024ed-411d-4a01-bdfb-43dfe18f5a6b,wsc5r0j,el02c6n,exazlvq,2irdgp0,NaN,z78nzkwb,640x360,0,...,2020-09-19 10:28:28.195,Roku,Digital Video player,InApp,NaN,5.61,0.0,10.0,i79zj-2z9zw,3ysyqec
10820543,2020-09-19 10:26:39,1ada9404-fa93-439a-93e4-052b61355b25,wsc5r0j,el02c6n,exazlvq,2irdgp0,NaN,z78nzkwb,640x360,0,...,2020-09-19 10:28:29.226,Roku,Digital Video player,InApp,NaN,NaN,NaN,NaN,i79zj-2z9zw,3ysyqec
10820544,2020-09-19 16:41:00,b7f41e07-19de-4677-99e4-1fad9c467875,wsc5r0j,el02c6n,exazlvq,2irdgp0,NaN,z78nzkwb,640x360,0,...,2020-09-19 16:44:49.579,Roku,Digital Video player,InApp,NaN,NaN,NaN,NaN,i79zj-2z9zw,3ysyqec

In [9]:
first = first.append(second)
first

,log_entry_time,impression_id,partner_id,campaign_id,ad_group_id,private_contract_id,audience_id,creative_id,ad_format,frequency,...,processed_time,device_make,device_model,rendering_context,carrier_id,temperature_in_celsius_name,temperature_bucket_start_in_celsius_name,temperature_bucket_end_in_celsius_name,impression_placement_id,advertiser_id
0,2020-10-02 02:31:05,dd39a58b-935b-4b59-b1d2-293c34132185,wsc5r0j,pey7wjw,l16k4pm,x4wccoj,NaN,bkqbfyvb,640x360,5,...,2020-10-02 02:39:04.159,Amazon,AFTMM,InApp,NaN,12.12,10.0,18.0,NaN,3ysyqec
1,2020-10-02 11:06:09,9f33b60d-6ecf-44a2-b8d3-2f22c7be61e5,wsc5r0j,37mbq70,985jsza,vyhvbql,k7orynn,3j4iywjn,9544x9544,0,...,2020-10-02 11:15:36.586,Samsung,SM-G970U1,Other,NaN,15.28,10.0,18.0,50054,3ysyqec
2,2020-10-02 02:35:08,75339cae-023f-4530-b406-27e088e26c00,wsc5r0j,pey7wjw,l16k4pm,x4wccoj,NaN,bkqbfyvb,640x360,2,...,2020-10-02 02:39:17.864,LG,Smart+ TV,Other,NaN,17.11,10.0,18.0,NaN,3ysyqec
3,2020-10-02 02:32:31,c17ef430-9798-4479-8751-7b460b76cd56,wsc5r0j,el02c6n,exazlvq,2irdgp0,NaN,z78nzkwb,640x360,0,...,2020-10-02 02:39:21.849,Roku,Digital Video player,InApp,NaN,14.26,10.0,18.0,i79zj-2z9zw,3ysyqec
4,2020-10-02 02:32:54,3bc7ec45-7392-4fa0-848f-c5ae53388c55,wsc5r0j,37mbq70,985jsza,vyhvbql,k7orynn,e3ttvsvt,9544x9544,0,...,2020-10-02 02:39:22.396,Samsung,SM-G965U,Other,NaN,NaN,NaN,NaN,8019,3ysyqec
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10820540,2020-09-19 10:35:22,8d51f582-375b-435b-9b34-7f198c41d3d4,wsc5r0j,pey7wjw,fcucjsu,wt0zmqf,1qh4zg7,vwzako4t,640x360,4,...,2020-09-19 10:39:23.839,Roku,Digital Video player,InApp,NaN,9.15,0.0,10.0,NaN,3ysyqec
10820541,2020-09-19 03:32:45,03abcb43-59b4-4b3e-b024-736d504b1e5c,wsc5r0j,pey7wjw,fcucjsu,wt0zmqf,1qh4zg7,vwzako4t,640x360,4,...,2020-09-19 03:37:32.437,Microsoft,XBOX One,InApp,NaN,26.87,24.0,30.0,NaN,3ysyqec
10820542,2020-09-19 10:22:29,a9b024ed-411d-4a01-bdfb-43dfe18f5a6b,wsc5r0j,el02c6n,exazlvq,2irdgp0,NaN,z78nzkwb,640x360,0,...,2020-09-19 10:28:28.195,Roku,Digital Video player,InApp,NaN,5.61,0.0,10.0,i79zj-2z9zw,3ysyqec
10820543,2020-09-19 10:26:39,1ada9404-fa93-439a-93e4-052b61355b25,wsc5r0j,el02c6n,exazlvq,2irdgp0,NaN,z78nzkwb,640x360,0,...,2020-09-19 10:28:29.226,Roku,Digital Video player,InApp,NaN,NaN,NaN,NaN,i79zj-2z9zw,3ysyqec
10820544,2020-09-19 16:41:00,b7f41e07-19de-4677-99e4-1fad9c467875,wsc5r0j,el02c6n,exazlvq,2irdgp0,NaN,z78nzkwb,640x360,0,...,2020-09-19 16:44:49.579,Roku,Digital Video player,InApp,NaN,NaN,NaN,NaN,i79zj-2z9zw,3ysyqec

In [10]:
first.dropna(subset=['zip_code'], inplace=True)
first.reset_index(drop=True, inplace=True)
first.head()

,log_entry_time,impression_id,partner_id,campaign_id,ad_group_id,private_contract_id,audience_id,creative_id,ad_format,frequency,...,processed_time,device_make,device_model,rendering_context,carrier_id,temperature_in_celsius_name,temperature_bucket_start_in_celsius_name,temperature_bucket_end_in_celsius_name,impression_placement_id,advertiser_id
0,2020-10-02 02:31:05,dd39a58b-935b-4b59-b1d2-293c34132185,wsc5r0j,pey7wjw,l16k4pm,x4wccoj,NaN,bkqbfyvb,640x360,5,...,2020-10-02 02:39:04.159,Amazon,AFTMM,InApp,NaN,12.12,10.0,18.0,NaN,3ysyqec
1,2020-10-02 11:06:09,9f33b60d-6ecf-44a2-b8d3-2f22c7be61e5,wsc5r0j,37mbq70,985jsza,vyhvbql,k7orynn,3j4iywjn,9544x9544,0,...,2020-10-02 11:15:36.586,Samsung,SM-G970U1,Other,NaN,15.28,10.0,18.0,50054,3ysyqec
2,2020-10-02 02:35:08,75339cae-023f-4530-b406-27e088e26c00,wsc5r0j,pey7wjw,l16k4pm,x4wccoj,NaN,bkqbfyvb,640x360,2,...,2020-10-02 02:39:17.864,LG,Smart+ TV,Other,NaN,17.11,10.0,18.0,NaN,3ysyqec
3,2020-10-02 02:32:31,c17ef430-9798-4479-8751-7b460b76cd56,wsc5r0j,el02c6n,exazlvq,2irdgp0,NaN,z78nzkwb,640x360,0,...,2020-10-02 02:39:21.849,Roku,Digital Video player,InApp,NaN,14.26,10.0,18.0,i79zj-2z9zw,3ysyqec
4,2020-10-02 02:32:54,3bc7ec45-7392-4fa0-848f-c5ae53388c55,wsc5r0j,37mbq70,985jsza,vyhvbql,k7orynn,e3ttvsvt,9544x9544,0,...,2020-10-02 02:39:22.396,Samsung,SM-G965U,Other,NaN,NaN,NaN,NaN,8019,3ysyqec

In [11]:
first

,log_entry_time,impression_id,partner_id,campaign_id,ad_group_id,private_contract_id,audience_id,creative_id,ad_format,frequency,...,processed_time,device_make,device_model,rendering_context,carrier_id,temperature_in_celsius_name,temperature_bucket_start_in_celsius_name,temperature_bucket_end_in_celsius_name,impression_placement_id,advertiser_id
0,2020-10-02 02:31:05,dd39a58b-935b-4b59-b1d2-293c34132185,wsc5r0j,pey7wjw,l16k4pm,x4wccoj,NaN,bkqbfyvb,640x360,5,...,2020-10-02 02:39:04.159,Amazon,AFTMM,InApp,NaN,12.12,10.0,18.0,NaN,3ysyqec
1,2020-10-02 11:06:09,9f33b60d-6ecf-44a2-b8d3-2f22c7be61e5,wsc5r0j,37mbq70,985jsza,vyhvbql,k7orynn,3j4iywjn,9544x9544,0,...,2020-10-02 11:15:36.586,Samsung,SM-G970U1,Other,NaN,15.28,10.0,18.0,50054,3ysyqec
2,2020-10-02 02:35:08,75339cae-023f-4530-b406-27e088e26c00,wsc5r0j,pey7wjw,l16k4pm,x4wccoj,NaN,bkqbfyvb,640x360,2,...,2020-10-02 02:39:17.864,LG,Smart+ TV,Other,NaN,17.11,10.0,18.0,NaN,3ysyqec
3,2020-10-02 02:32:31,c17ef430-9798-4479-8751-7b460b76cd56,wsc5r0j,el02c6n,exazlvq,2irdgp0,NaN,z78nzkwb,640x360,0,...,2020-10-02 02:39:21.849,Roku,Digital Video player,InApp,NaN,14.26,10.0,18.0,i79zj-2z9zw,3ysyqec
4,2020-10-02 02:32:54,3bc7ec45-7392-4fa0-848f-c5ae53388c55,wsc5r0j,37mbq70,985jsza,vyhvbql,k7orynn,e3ttvsvt,9544x9544,0,...,2020-10-02 02:39:22.396,Samsung,SM-G965U,Other,NaN,NaN,NaN,NaN,8019,3ysyqec
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23391424,2020-09-19 10:35:22,8d51f582-375b-435b-9b34-7f198c41d3d4,wsc5r0j,pey7wjw,fcucjsu,wt0zmqf,1qh4zg7,vwzako4t,640x360,4,...,2020-09-19 10:39:23.839,Roku,Digital Video player,InApp,NaN,9.15,0.0,10.0,NaN,3ysyqec
23391425,2020-09-19 03:32:45,03abcb43-59b4-4b3e-b024-736d504b1e5c,wsc5r0j,pey7wjw,fcucjsu,wt0zmqf,1qh4zg7,vwzako4t,640x360,4,...,2020-09-19 03:37:32.437,Microsoft,XBOX One,InApp,NaN,26.87,24.0,30.0,NaN,3ysyqec
23391426,2020-09-19 10:22:29,a9b024ed-411d-4a01-bdfb-43dfe18f5a6b,wsc5r0j,el02c6n,exazlvq,2irdgp0,NaN,z78nzkwb,640x360,0,...,2020-09-19 10:28:28.195,Roku,Digital Video player,InApp,NaN,5.61,0.0,10.0,i79zj-2z9zw,3ysyqec
23391427,2020-09-19 10:26:39,1ada9404-fa93-439a-93e4-052b61355b25,wsc5r0j,el02c6n,exazlvq,2irdgp0,NaN,z78nzkwb,640x360,0,...,2020-09-19 10:28:29.226,Roku,Digital Video player,InApp,NaN,NaN,NaN,NaN,i79zj-2z9zw,3ysyqec
23391428,2020-09-19 16:41:00,b7f41e07-19de-4677-99e4-1fad9c467875,wsc5r0j,el02c6n,exazlvq,2irdgp0,NaN,z78nzkwb,640x360,0,...,2020-09-19 16:44:49.579,Roku,Digital Video player,InApp,NaN,NaN,NaN,NaN,i79zj-2z9zw,3ysyqec

In [12]:
first.describe()

,frequency,fold_position,user_hour_of_week,metro,device_type,os_family,os,browser,recency,language_code,...,ttd_cost_in_usd,partner_cost_in_usd,advertiser_cost_in_usd,latitude,longitude,zip_code,carrier_id,temperature_in_celsius_name,temperature_bucket_start_in_celsius_name,temperature_bucket_end_in_celsius_name
count,2.339143e+07,2.339143e+07,2.339053e+07,2.339017e+07,2.339143e+07,2.337489e+07,2.337489e+07,2.337489e+07,1.748895e+06,0.0,...,2.339143e+07,2.339143e+07,2.339143e+07,1.728882e+07,1.728882e+07,2.339143e+07,19524.000000,1.477804e+07,1.477772e+07,1.474803e+07
mean,1.857286e+00,3.937709e+00,9.012133e+01,6.053171e+02,5.679640e+00,2.953424e+00,1.138467e+02,4.383178e+00,1.405745e+04,NaN,...,2.468209e-02,2.693777e-02,2.693777e-02,3.733107e+01,-9.002384e+01,4.691981e+04,369.078007,1.839183e+01,1.458281e+01,2.175543e+01
std,2.953856e+00,3.470326e-01,4.460568e+01,1.004483e+02,9.400369e-01,2.278157e+00,1.997285e+01,4.893248e+00,1.456744e+04,NaN,...,7.858296e-03,8.898514e-03,8.898514e-03,4.978030e+00,1.461346e+01,2.682952e+04,221.470177,6.474208e+00,7.554893e+00,6.433745e+00
min,0.000000e+00,2.000000e+00,0.000000e+00,5.000000e+02,1.000000e+00,1.000000e+00,1.010000e+02,1.000000e+00,0.000000e+00,NaN,...,1.600800e-05,5.738800e-05,5.738800e-05,-3.393000e+01,-1.665400e+02,1.001000e+03,32.000000,-1.800000e+01,-1.000000e+01,-1.000000e+01
25%,0.000000e+00,4.000000e+00,5.500000e+01,5.240000e+02,6.000000e+00,1.000000e+00,1.010000e+02,1.000000e+00,4.601000e+03,NaN,...,1.877000e-02,1.960944e-02,1.960944e-02,3.373000e+01,-9.609000e+01,2.780400e+04,32.000000,1.401000e+01,1.000000e+01,1.800000e+01
50%,0.000000e+00,4.000000e+00,9.500000e+01,5.700000e+02,6.000000e+00,1.000000e+00,1.010000e+02,1.000000e+00,1.138900e+04,NaN,...,2.516816e-02,2.786747e-02,2.786747e-02,3.801000e+01,-8.605000e+01,4.304000e+04,509.000000,1.837000e+01,1.800000e+01,2.400000e+01
75%,3.000000e+00,4.000000e+00,1.240000e+02,6.520000e+02,6.000000e+00,6.000000e+00,1.400000e+02,6.000000e+00,1.889300e+04,NaN,...,2.990000e-02,3.307250e-02,3.307250e-02,4.092000e+01,-8.014000e+01,7.060500e+04,509.000000,2.275000e+01,1.800000e+01,2.400000e+01
max,1.100000e+01,4.000000e+00,1.670000e+02,8.810000e+02,6.000000e+00,7.000000e+00,1.700000e+02,1.500000e+01,2.590390e+05,NaN,...,4.340000e-02,4.792250e-02,4.792250e-02,7.123000e+01,1.511900e+02,9.992900e+04,553.000000,4.458000e+01,3.800000e+01,3.800000e+01

In [16]:
data_clean = first.drop(columns=['log_entry_time', 'partner_id', 
                                                             'private_contract_id', 'creative_id', 'ad_format',
                                                             'frequency', 'supply_vendor_publisher_id', 'deal_id',
                                                             'site', 'referrer_categories_list', 'fold_position',
                                                             'user_hour_of_week', 'ip_address', 'metro', 
                                                             'recency', 'language_code',  
                                                             'processed_time', 'rendering_context', 
                                                             'temperature_in_celsius_name', 
                                                             'temperature_bucket_start_in_celsius_name', 
                                                             'temperature_bucket_end_in_celsius_name', 
                                                             'impression_placement_id', 
                                                             'advertiser_id', 'carrier_id', 'impression_id'])

In [19]:
data_clean

,campaign_id,ad_group_id,audience_id,supply_vendor,user_agent,country,region,city,device_type,os_family,...,fee_feature_cost,data_usage_total_cost,ttd_cost_in_usd,partner_cost_in_usd,advertiser_cost_in_usd,latitude,longitude,zip_code,device_make,device_model
0,pey7wjw,l16k4pm,NaN,freewheel,Dalvik/2.1.0 (Linux; U; Android 7.1.2; AFTMM B...,United States,Kansas,Mission,6,6.0,...,0.000182,0.00000,0.02900,0.032082,0.032082,39.02,-94.65,66202.0,Amazon,AFTMM
1,37mbq70,985jsza,k7orynn,triplelift,Mozilla/5.0 (Linux; Android 10; SAMSUNG SM-G97...,United States,Alabama,Fairhope,4,6.0,...,0.000040,0.00112,0.00812,0.008860,0.008860,30.50,-87.87,36532.0,Samsung,SM-G970U1
2,pey7wjw,l16k4pm,NaN,freewheel,Mozilla/5.0 (Web0S; Linux/SmartTV) AppleWebKit...,United States,Pennsylvania,Philadelphia,6,4.0,...,0.000182,0.00000,0.02900,0.032082,0.032082,40.05,-75.18,19119.0,LG,Smart+ TV
3,el02c6n,exazlvq,NaN,Telaria,Roku/DVP-9.30 (909.30E04194A),United States,Pennsylvania,Reading,6,1.0,...,0.000182,0.00000,0.01877,0.019609,0.019609,NaN,NaN,19606.0,Roku,Digital Video player
4,37mbq70,985jsza,k7orynn,triplelift,Mozilla/5.0 (Linux; Android 10; SM-G965U Build...,United States,Massachusetts,Cambridge,4,6.0,...,0.000040,0.00140,0.00840,0.009140,0.009140,42.36,-71.09,2139.0,Samsung,SM-G965U
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23391424,pey7wjw,fcucjsu,1qh4zg7,freewheel,Roku/DVP-9.30 (049.30E04194A),United States,Pennsylvania,Upper Darby,6,1.0,...,0.000182,0.00000,0.03840,0.042422,0.042422,39.95,-75.27,19082.0,Roku,Digital Video player
23391425,pey7wjw,fcucjsu,1qh4zg7,freewheel,Mozilla/5.0 (Windows NT 10.0; Win64; x64; Xbox...,United States,Utah,Salt Lake City,6,2.0,...,0.000182,0.00000,0.03840,0.042422,0.042422,40.65,-111.91,84123.0,Microsoft,XBOX One
23391426,el02c6n,exazlvq,NaN,Telaria,Roku/DVP-9.30 (249.30E04194A),United States,Ohio,Delaware,6,1.0,...,0.000182,0.00000,0.01877,0.019609,0.019609,NaN,NaN,43015.0,Roku,Digital Video player
23391427,el02c6n,exazlvq,NaN,Telaria,Roku/DVP-9.30 (509.30E04194A),United States,Georgia,Cedartown,6,1.0,...,0.000182,0.00000,0.01877,0.019609,0.019609,NaN,NaN,30125.0,Roku,Digital Video player
23391428,el02c6n,exazlvq,NaN,Telaria,Roku/DVP-9.30 (489.30E04194A),United States,Georgia,Lithonia,6,1.0,...,0.000182,0.00000,0.01877,0.019609,0.019609,NaN,NaN,30058.0,Roku,Digital Video player

In [20]:
demo = pd.read_csv('demo.csv')
demo

,Unnamed: 0,zipcode,age,ethnicity,income,count
0,0,601,18-23,Hispanic,"$1,000 - $14,999",1
1,1,601,24-29,Hispanic,"$1,000 - $14,999",5
2,2,601,24-29,White,"$1,000 - $14,999",2
3,3,601,30-35,Hispanic,"$1,000 - $14,999",20
4,4,601,30-35,Hispanic,"$15,000 - $19,999",1
...,...,...,...,...,...,...
7827655,10412,99929,not_reported,White,"$40,000 - $49,999",7
7827656,10413,99929,not_reported,White,"$50,000 - $74,999",12
7827657,10414,99929,not_reported,White,"$75,000 - $99,999",3
7827658,10415,99929,not_reported,White,not_reported,7
7827659,10416,99929,not_reported,not_reported,"$50,000 - $74,999",1

In [22]:
demo_pop = demo['count'].sum()
demo_pop_by_zip = demo.groupby(['zipcode']).agg({'count': 'sum'})
demo_pop_by_zip.rename(columns={"count": "household_count"}, inplace=True)
demo_pop_by_zip['household_count'] = demo_pop_by_zip['household_count'].astype(float)
demo_pop_by_zip['expected_zip_freq'] = demo_pop_by_zip['household_count'] / demo_pop
demo_pop_by_zip.head()

         household_count  expected_zip_freq
zipcode
601               2049.0           0.000008
602               4002.0           0.000016
603               4528.0           0.000018
604                621.0           0.000003
605               2202.0           0.000009

In [24]:
imp_by_zip = pd.DataFrame(data_clean['zip_code'].value_counts()).reset_index().rename(columns={"zip_code": "impression_count", "index": "zip_code"})
imp_by_zip['zip_code'] = imp_by_zip['zip_code'].astype(int)
imp_by_zip.set_index('zip_code', inplace=True)
imp_by_zip['observed_zip_freq'] = data_clean['zip_code'].value_counts(normalize=True)
imp_by_zip.head()

          impression_count  observed_zip_freq
zip_code
36117                21317           0.000911
20149                21179           0.000905
65203                18178           0.000777
37042                16094           0.000688
63033                15706           0.000671

In [25]:
pd.concat([imp_by_zip, demo_pop_by_zip], axis=1, join='outer', sort=False)

       impression_count  observed_zip_freq  household_count  expected_zip_freq
601                 NaN                NaN           2049.0       8.291932e-06
602                 NaN                NaN           4002.0       1.619537e-05
603                 NaN                NaN           4528.0       1.832400e-05
604                 NaN                NaN            621.0       2.513074e-06
605                 NaN                NaN           2202.0       8.911095e-06
...                 ...                ...              ...                ...
99925               7.0       2.992549e-07            660.0       2.670900e-06
99926              21.0       8.977647e-07           1050.0       4.249160e-06
99927               NaN                NaN             43.0       1.740132e-07
99928               NaN                NaN            894.0       3.617856e-06
99929              65.0       2.778796e-06           1688.0       6.831030e-06

[39285 rows x 4 columns]

In [26]:
joined_for_measurement = imp_by_zip.join(demo_pop_by_zip).dropna()
joined_for_measurement

,impression_count,observed_zip_freq,household_count,expected_zip_freq
zip_code,,,,
36117,21317,9.113167e-04,47124.0,1.907023e-04
65203,18178,7.771223e-04,44838.0,1.814513e-04
37042,16094,6.880298e-04,62249.0,2.519104e-04
63033,15706,6.714425e-04,35101.0,1.420474e-04
29501,14722,6.293758e-04,34618.0,1.400928e-04
...,...,...,...,...
79846,1,4.275070e-08,36.0,1.456855e-07
21869,1,4.275070e-08,687.0,2.780164e-06
49853,1,4.275070e-08,1008.0,4.079193e-06
41098,1,4.275070e-08,1128.0,4.564811e-06
98228,1,4.275070e-08,1327.0,5.370128e-06

In [27]:
total_no = len(data_clean)

joined_for_measurement['expected count'] = joined_for_measurement['expected_zip_freq']*total_no
joined_for_measurement['observed count'] = joined_for_measurement['observed_zip_freq']*total_no

E_sub_O_sq = (joined_for_measurement['observed count'].dropna() - joined_for_measurement['expected count'].dropna())**2
chisq_rs = sum(E_sub_O_sq/joined_for_measurement['expected count'])
chisq_rs

426836114.7511034

In [28]:

region = data_clean[['region', 'zip_code']].drop_duplicates()
map_zip_to_region = region.set_index('zip_code').to_dict().get('region')

In [29]:
demo['region'] = demo['zipcode'].map(map_zip_to_region)
demo.dropna()

,Unnamed: 0,zipcode,age,ethnicity,income,count,region
19217,19217,1001,18-23,African American,"$125,000 - $149,999",1,Massachusetts
19218,19218,1001,18-23,African American,"$20,000 - $29,999",4,Massachusetts
19219,19219,1001,18-23,African American,"$30,000 - $39,999",1,Massachusetts
19220,19220,1001,18-23,African American,"$50,000 - $74,999",2,Massachusetts
19221,19221,1001,18-23,Asian,"$20,000 - $29,999",1,Massachusetts
...,...,...,...,...,...,...,...
7827655,10412,99929,not_reported,White,"$40,000 - $49,999",7,Alaska
7827656,10413,99929,not_reported,White,"$50,000 - $74,999",12,Alaska
7827657,10414,99929,not_reported,White,"$75,000 - $99,999",3,Alaska
7827658,10415,99929,not_reported,White,not_reported,7,Alaska
7827659,10416,99929,not_reported,not_reported,"$50,000 - $74,999",1,Alaska

In [30]:
imp_region = pd.DataFrame(data_clean['region'].value_counts(normalize=True)).reset_index()
imp_region.rename(columns={"index": "region", "region": "imp_region_frequency"}, inplace=True)
imp_region

##question here: the joined table matches where the zip codes are the same... should the proportion in the demographic data and imp zip code freuqncy be adjusted so that it is the proportion just including the zip codes where they match?
demo_region = pd.DataFrame(demo['region'].value_counts(normalize=True)).reset_index()
demo_region.rename(columns={"index": "region", "region": "demo_region_frequency"}, inplace=True)

imp_region.set_index('region', inplace=True)
demo_region.set_index('region', inplace=True)

joined = imp_region.join(demo_region).dropna()
joined

                      imp_region_frequency  demo_region_frequency
region
Texas                             0.074147               0.074262
New York                          0.059965               0.057043
California                        0.059381               0.074722
Florida                           0.056374               0.051873
Ohio                              0.053596               0.036985
Georgia                           0.045114               0.028490
North Carolina                    0.040472               0.031310
Illinois                          0.039115               0.039394
Pennsylvania                      0.036628               0.042606
Tennessee                         0.035236               0.020216
Virginia                          0.030679               0.028017
Michigan                          0.029935               0.033332
Indiana                           0.027813               0.021535
Missouri                          0.025312               0.022893
Alabama                           0.024991               0.019683
South Carolina                    0.024660               0.015184
New Jersey                        0.023901               0.028569
Maryland                          0.022099               0.018162
Kentucky                          0.021489               0.016582
Louisiana                         0.020770               0.016821
Wisconsin                         0.017198               0.021710
Massachusetts                     0.016789               0.023050
Washington                        0.016422               0.021035
Mississippi                       0.016111               0.012087
Minnesota                         0.015931               0.023336
Arkansas                          0.013130               0.012872
Connecticut                       0.012525               0.012622
Oklahoma                          0.012090               0.015985
Arizona                           0.011950               0.015100
Colorado                          0.011312               0.017187
Oregon                            0.011215               0.012247
Kansas                            0.009692               0.014182
Nevada                            0.008917               0.007099
West Virginia                     0.008809               0.010400
Iowa                              0.007891               0.018893
Nebraska                          0.006364               0.010925
Utah                              0.005901               0.007802
New Mexico                        0.005143               0.006467
Idaho                             0.005013               0.006398
Maine                             0.004634               0.008191
Delaware                          0.004439               0.003182
Rhode Island                      0.004102               0.003384
District of Columbia              0.003701               0.001290
New Hampshire                     0.003669               0.006585
South Dakota                      0.002851               0.005857
North Dakota                      0.002793               0.004999
Hawaii                            0.002505               0.003583
Vermont                           0.002322               0.004930
Wyoming                           0.002017               0.002851
Alaska                            0.001476               0.003214
Montana                           0.001412               0.004858

In [31]:
total_no = len(data_clean)

joined['expected freq'] = joined['demo_region_frequency']*total_no
joined['observed freq'] = data_clean['region'].value_counts()

E_sub_O_sq = (joined['observed freq'].dropna() - joined['expected freq'].dropna())**2
chisq_rs = sum(E_sub_O_sq/joined['expected freq'])
chisq_rs

2056425.342115203

In [34]:
imp_Iowa = data_clean[data_clean['region']=='Iowa']

In [2]:
joined = pd.read_csv('joined.csv')
joined

,region,imp_region_frequency,demo_region_frequency,expected freq,observed freq
0,Texas,0.074147,0.074262,1.737093e+06,1734348
1,New York,0.059965,0.057043,1.334328e+06,1402615
2,California,0.059381,0.074722,1.747851e+06,1388956
3,Florida,0.056374,0.051873,1.213392e+06,1318625
4,Ohio,0.053596,0.036985,8.651342e+05,1253649
5,Georgia,0.045114,0.028490,6.664293e+05,1055238
6,North Carolina,0.040472,0.031310,7.323935e+05,946652
7,Illinois,0.039115,0.039394,9.214862e+05,914912
8,Pennsylvania,0.036628,0.042606,9.966188e+05,856759
9,Tennessee,0.035236,0.020216,4.728797e+05,824189
10,Virginia,0.030679,0.028017,6.553475e+05,717589
11,Michigan,0.029935,0.033332,7.796805e+05,700185
12,Indiana,0.027813,0.021535,5.037402e+05,650561
13,Missouri,0.025312,0.022893,5.354885e+05,592070
14,Alabama,0.024991,0.019683,4.604179e+05,584557
15,South Carolina,0.024660,0.015184,3.551649e+05,576821
16,New Jersey,0.023901,0.028569,6.682602e+05,559050
17,Maryland,0.022099,0.018162,4.248391e+05,516897
18,Kentucky,0.021489,0.016582,3.878665e+05,502631
19,Louisiana,0.020770,0.016821,3.934693e+05,485832
20,Wisconsin,0.017198,0.021710,5.078218e+05,402269
21,Massachusetts,0.016789,0.023050,5.391709e+05,392712
22,Washington,0.016422,0.021035,4.920354e+05,384113
23,Mississippi,0.016111,0.012087,2.827374e+05,376834
24,Minnesota,0.015931,0.023336,5.458544e+05,372645
25,Arkansas,0.013130,0.012872,3.010912e+05,307115
26,Connecticut,0.012525,0.012622,2.952405e+05,292973
27,Oklahoma,0.012090,0.015985,3.739110e+05,282781
28,Arizona,0.011950,0.015100,3.532204e+05,279516
29,Colorado,0.011312,0.017187,4.020285e+05,264604
30,Oregon,0.011215,0.012247,2.864749e+05,262318
31,Kansas,0.009692,0.014182,3.317382e+05,226698
32,Nevada,0.008917,0.007099,1.660584e+05,208562
33,West Virginia,0.008809,0.010400,2.432765e+05,206041
34,Iowa,0.007891,0.018893,4.419299e+05,184574
35,Nebraska,0.006364,0.010925,2.555422e+05,148865
36,Utah,0.005901,0.007802,1.825056e+05,138035
37,New Mexico,0.005143,0.006467,1.512735e+05,120295
38,Idaho,0.005013,0.006398,1.496697e+05,117265
39,Maine,0.004634,0.008191,1.916050e+05,108400
40,Delaware,0.004439,0.003182,7.442359e+04,103825
41,Rhode Island,0.004102,0.003384,7.916605e+04,95941
42,District of Columbia,0.003701,0.001290,3.016866e+04,86569
43,New Hampshire,0.003669,0.006585,1.540336e+05,85810
44,South Dakota,0.002851,0.005857,1.370014e+05,66692
45,North Dakota,0.002793,0.004999,1.169268e+05,65319
46,Hawaii,0.002505,0.003583,8.381559e+04,58588
47,Vermont,0.002322,0.004930,1.153299e+05,54305
48,Wyoming,0.002017,0.002851,6.668354e+04,47172
49,Alaska,0.001476,0.003214,7.517385e+04,34536
50,Montana,0.001412,0.004858,1.136401e+05,33025

In [3]:
joined['bias']=''

In [4]:
joined

,region,imp_region_frequency,demo_region_frequency,expected freq,observed freq,bias
0,Texas,0.074147,0.074262,1.737093e+06,1734348,
1,New York,0.059965,0.057043,1.334328e+06,1402615,
2,California,0.059381,0.074722,1.747851e+06,1388956,
3,Florida,0.056374,0.051873,1.213392e+06,1318625,
4,Ohio,0.053596,0.036985,8.651342e+05,1253649,
5,Georgia,0.045114,0.028490,6.664293e+05,1055238,
6,North Carolina,0.040472,0.031310,7.323935e+05,946652,
7,Illinois,0.039115,0.039394,9.214862e+05,914912,
8,Pennsylvania,0.036628,0.042606,9.966188e+05,856759,
9,Tennessee,0.035236,0.020216,4.728797e+05,824189,
10,Virginia,0.030679,0.028017,6.553475e+05,717589,
11,Michigan,0.029935,0.033332,7.796805e+05,700185,
12,Indiana,0.027813,0.021535,5.037402e+05,650561,
13,Missouri,0.025312,0.022893,5.354885e+05,592070,
14,Alabama,0.024991,0.019683,4.604179e+05,584557,
15,South Carolina,0.024660,0.015184,3.551649e+05,576821,
16,New Jersey,0.023901,0.028569,6.682602e+05,559050,
17,Maryland,0.022099,0.018162,4.248391e+05,516897,
18,Kentucky,0.021489,0.016582,3.878665e+05,502631,
19,Louisiana,0.020770,0.016821,3.934693e+05,485832,
20,Wisconsin,0.017198,0.021710,5.078218e+05,402269,
21,Massachusetts,0.016789,0.023050,5.391709e+05,392712,
22,Washington,0.016422,0.021035,4.920354e+05,384113,
23,Mississippi,0.016111,0.012087,2.827374e+05,376834,
24,Minnesota,0.015931,0.023336,5.458544e+05,372645,
25,Arkansas,0.013130,0.012872,3.010912e+05,307115,
26,Connecticut,0.012525,0.012622,2.952405e+05,292973,
27,Oklahoma,0.012090,0.015985,3.739110e+05,282781,
28,Arizona,0.011950,0.015100,3.532204e+05,279516,
29,Colorado,0.011312,0.017187,4.020285e+05,264604,
30,Oregon,0.011215,0.012247,2.864749e+05,262318,
31,Kansas,0.009692,0.014182,3.317382e+05,226698,
32,Nevada,0.008917,0.007099,1.660584e+05,208562,
33,West Virginia,0.008809,0.010400,2.432765e+05,206041,
34,Iowa,0.007891,0.018893,4.419299e+05,184574,
35,Nebraska,0.006364,0.010925,2.555422e+05,148865,
36,Utah,0.005901,0.007802,1.825056e+05,138035,
37,New Mexico,0.005143,0.006467,1.512735e+05,120295,
38,Idaho,0.005013,0.006398,1.496697e+05,117265,
39,Maine,0.004634,0.008191,1.916050e+05,108400,
40,Delaware,0.004439,0.003182,7.442359e+04,103825,
41,Rhode Island,0.004102,0.003384,7.916605e+04,95941,
42,District of Columbia,0.003701,0.001290,3.016866e+04,86569,
43,New Hampshire,0.003669,0.006585,1.540336e+05,85810,
44,South Dakota,0.002851,0.005857,1.370014e+05,66692,
45,North Dakota,0.002793,0.004999,1.169268e+05,65319,
46,Hawaii,0.002505,0.003583,8.381559e+04,58588,
47,Vermont,0.002322,0.004930,1.153299e+05,54305,
48,Wyoming,0.002017,0.002851,6.668354e+04,47172,
49,Alaska,0.001476,0.003214,7.517385e+04,34536,
50,Montana,0.001412,0.004858,1.136401e+05,33025,

In [5]:
joined['bias']=(joined['observed freq']-joined['expected freq'])/joined['expected freq']
joined

,region,imp_region_frequency,demo_region_frequency,expected freq,observed freq,bias
0,Texas,0.074147,0.074262,1.737093e+06,1734348,-0.001580
1,New York,0.059965,0.057043,1.334328e+06,1402615,0.051177
2,California,0.059381,0.074722,1.747851e+06,1388956,-0.205335
3,Florida,0.056374,0.051873,1.213392e+06,1318625,0.086726
4,Ohio,0.053596,0.036985,8.651342e+05,1253649,0.449080
5,Georgia,0.045114,0.028490,6.664293e+05,1055238,0.583421
6,North Carolina,0.040472,0.031310,7.323935e+05,946652,0.292546
7,Illinois,0.039115,0.039394,9.214862e+05,914912,-0.007134
8,Pennsylvania,0.036628,0.042606,9.966188e+05,856759,-0.140334
9,Tennessee,0.035236,0.020216,4.728797e+05,824189,0.742915
10,Virginia,0.030679,0.028017,6.553475e+05,717589,0.094975
11,Michigan,0.029935,0.033332,7.796805e+05,700185,-0.101959
12,Indiana,0.027813,0.021535,5.037402e+05,650561,0.291461
13,Missouri,0.025312,0.022893,5.354885e+05,592070,0.105663
14,Alabama,0.024991,0.019683,4.604179e+05,584557,0.269623
15,South Carolina,0.024660,0.015184,3.551649e+05,576821,0.624094
16,New Jersey,0.023901,0.028569,6.682602e+05,559050,-0.163425
17,Maryland,0.022099,0.018162,4.248391e+05,516897,0.216689
18,Kentucky,0.021489,0.016582,3.878665e+05,502631,0.295887
19,Louisiana,0.020770,0.016821,3.934693e+05,485832,0.234739
20,Wisconsin,0.017198,0.021710,5.078218e+05,402269,-0.207854
21,Massachusetts,0.016789,0.023050,5.391709e+05,392712,-0.271637
22,Washington,0.016422,0.021035,4.920354e+05,384113,-0.219339
23,Mississippi,0.016111,0.012087,2.827374e+05,376834,0.332806
24,Minnesota,0.015931,0.023336,5.458544e+05,372645,-0.317318
25,Arkansas,0.013130,0.012872,3.010912e+05,307115,0.020007
26,Connecticut,0.012525,0.012622,2.952405e+05,292973,-0.007680
27,Oklahoma,0.012090,0.015985,3.739110e+05,282781,-0.243721
28,Arizona,0.011950,0.015100,3.532204e+05,279516,-0.208664
29,Colorado,0.011312,0.017187,4.020285e+05,264604,-0.341828
30,Oregon,0.011215,0.012247,2.864749e+05,262318,-0.084325
31,Kansas,0.009692,0.014182,3.317382e+05,226698,-0.316636
32,Nevada,0.008917,0.007099,1.660584e+05,208562,0.255956
33,West Virginia,0.008809,0.010400,2.432765e+05,206041,-0.153058
34,Iowa,0.007891,0.018893,4.419299e+05,184574,-0.582345
35,Nebraska,0.006364,0.010925,2.555422e+05,148865,-0.417454
36,Utah,0.005901,0.007802,1.825056e+05,138035,-0.243667
37,New Mexico,0.005143,0.006467,1.512735e+05,120295,-0.204785
38,Idaho,0.005013,0.006398,1.496697e+05,117265,-0.216508
39,Maine,0.004634,0.008191,1.916050e+05,108400,-0.434253
40,Delaware,0.004439,0.003182,7.442359e+04,103825,0.395055
41,Rhode Island,0.004102,0.003384,7.916605e+04,95941,0.211896
42,District of Columbia,0.003701,0.001290,3.016866e+04,86569,1.869501
43,New Hampshire,0.003669,0.006585,1.540336e+05,85810,-0.442914
44,South Dakota,0.002851,0.005857,1.370014e+05,66692,-0.513202
45,North Dakota,0.002793,0.004999,1.169268e+05,65319,-0.441368
46,Hawaii,0.002505,0.003583,8.381559e+04,58588,-0.300989
47,Vermont,0.002322,0.004930,1.153299e+05,54305,-0.529133
48,Wyoming,0.002017,0.002851,6.668354e+04,47172,-0.292599
49,Alaska,0.001476,0.003214,7.517385e+04,34536,-0.540585
50,Montana,0.001412,0.004858,1.136401e+05,33025,-0.709390